rootProject.name = "ProzenExtension"
include(":common")
include(":page")
include(":content")
include(":popup")
include(":search")
include(":status")
include(":settings")
include(":service-worker")
include(":chrome")
include(":prozen")
include(":prozen-firefox")